// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_A2j-nhIL-c2y9GpP__PH1x6g5eh1OIg',
    appId: '1:430474804231:web:21cc5803986420b85a3ea2',
    messagingSenderId: '430474804231',
    projectId: 'chat-app-e2a79',
    authDomain: 'chat-app-e2a79.firebaseapp.com',
    storageBucket: 'chat-app-e2a79.appspot.com',
    measurementId: 'G-TH74KTKBGL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzSbYEnq2nWSoYHRpJ9-3FW6biJzrz3tg',
    appId: '1:430474804231:android:15ae2734e3efae025a3ea2',
    messagingSenderId: '430474804231',
    projectId: 'chat-app-e2a79',
    storageBucket: 'chat-app-e2a79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjouiLdEZIcn2EKa1P_-s0H87snXGFCMI',
    appId: '1:430474804231:ios:834d5f1d617e67fe5a3ea2',
    messagingSenderId: '430474804231',
    projectId: 'chat-app-e2a79',
    storageBucket: 'chat-app-e2a79.appspot.com',
    iosBundleId: 'com.example.chatappMentor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjouiLdEZIcn2EKa1P_-s0H87snXGFCMI',
    appId: '1:430474804231:ios:834d5f1d617e67fe5a3ea2',
    messagingSenderId: '430474804231',
    projectId: 'chat-app-e2a79',
    storageBucket: 'chat-app-e2a79.appspot.com',
    iosBundleId: 'com.example.chatappMentor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_A2j-nhIL-c2y9GpP__PH1x6g5eh1OIg',
    appId: '1:430474804231:web:e1109084fa39e9815a3ea2',
    messagingSenderId: '430474804231',
    projectId: 'chat-app-e2a79',
    authDomain: 'chat-app-e2a79.firebaseapp.com',
    storageBucket: 'chat-app-e2a79.appspot.com',
    measurementId: 'G-W9L10RMNF3',
  );
}
